nome = str(input('Qual o seu nome? ')).strip()
quantidade = len(nome)-nome.count(' ')
quantidade1 = nome.find(' ')
min = nome.lower()
mai = nome.upper()
print('Quantidade de letras totais: {}'.format(quantidade))
print('Quantidade de letras no primeiro nome: {}'.format(quantidade1))
print('Nome em letras minúsculas: {}'.format(min))
print('Nome em letras maiúsculas: {}'.format(mai))